###
# @name GetFilms
GET https://localhost:5001/swapi/films
Accept: application/json

###
# @name GetPeople
GET https://localhost:5001/swapi/people


###
# @name GetVersion
GET https://localhost:5001/version

###
# @name GetAnError
GET https://localhost:5001/error

###
# @name GetFilmsDev
GET https://swapi-dotnet-dev.azurewebsites.net/swapi/films
Accept: application/json

###
# @name GetPeopleDev
GET https://swapi-dotnet-dev.azurewebsites.net/swapi/people


###
# @name GetVersionDev
GET https://swapi-dotnet-dev.azurewebsites.net/version